cmake_minimum_required(VERSION 3.25)

if(NOT DEFINED GFFX_SOURCE_DIR)
    message(FATAL_ERROR "GFFX_SOURCE_DIR must be defined")
endif()

file(READ "${GFFX_SOURCE_DIR}/CMakeLists.txt" root_cmake)
file(READ "${GFFX_SOURCE_DIR}/cmake/GffxCuda.cmake" cuda_cmake)
file(READ "${GFFX_SOURCE_DIR}/pyproject.toml" pyproject)
file(READ "${GFFX_SOURCE_DIR}/native/core/cuda_loader.c" loader_source)
file(READ "${GFFX_SOURCE_DIR}/native/cuda/plugin.c" plugin_source)

if(NOT root_cmake MATCHES "if[(]GFFX_ENABLE_CUDA[)][\r\n]+[ \t]*include[(]GffxCuda[)]")
    message(FATAL_ERROR "CUDA build module is not guarded by GFFX_ENABLE_CUDA")
endif()
if(NOT pyproject MATCHES "cmake[.]define[.]GFFX_ENABLE_CUDA[ \t]*=[ \t]*\"OFF\"")
    message(FATAL_ERROR "ordinary wheel builds are not explicitly CPU-only")
endif()
if(loader_source MATCHES "#[ \t]*include[ \t]*<cuda(_runtime)?[.]h>")
    message(FATAL_ERROR "the framework-neutral host loader includes CUDA headers")
endif()
if(NOT plugin_source MATCHES "#[ \t]*include[ \t]*<cuda[.]h>")
    message(FATAL_ERROR "the optional provider does not use the CUDA Driver API header")
endif()
if(plugin_source MATCHES "cuda_runtime[.]h|torch/|cublas|cudnn|nccl")
    message(FATAL_ERROR "the optional provider reaches a forbidden runtime/framework library")
endif()
if(NOT cuda_cmake MATCHES
   "target_link_libraries[(]gffx_cuda12 PRIVATE CUDA::cuda_driver[)]")
    message(FATAL_ERROR "the CUDA plugin is not linked solely through CUDA::cuda_driver")
endif()
if(cuda_cmake MATCHES "CUDA::(cudart|cublas|cudnn|nvrtc|nvJitLink)|torch")
    message(FATAL_ERROR "the CUDA build recipe links a forbidden optional dependency")
endif()

file(GLOB core_sources "${GFFX_SOURCE_DIR}/native/core/*.[ch]")
foreach(core_source IN LISTS core_sources)
    file(READ "${core_source}" core_text)
    if(core_text MATCHES "#[ \t]*include[ \t]*<cuda(_runtime)?[.]h>")
        message(FATAL_ERROR "CPU core includes CUDA: ${core_source}")
    endif()
endforeach()

message(STATUS "CUDA source/build isolation inspection passed")
