[build-system]
requires      = [
    "scikit-build-core",
    "pybind11"
]
build-backend = "scikit_build_core.build"

[project]
name = "gffx"
version = "0.1.3"
dependencies = [
    'torch',
    'matplotlib',
    'tqdm',
    'pytest'
]
authors = [
    {name = "Danzel Serrano", email = "danzel.serrano@gmail.com"}
]
description = "a minimal differentiable graphics library (meshes, rendering)"

[tool.scikit-build]
cmake.verbose = true