[build-system]
requires      = ["setuptools", "pytest"]
build-backend = "setuptools.build_meta"

[project]
name = "gffx"
version = "0.1.3"
dependencies = [
    'torch',
]
authors = [
    {name = "Danzel Serrano", email = "danzel.serrano@gmail.com"}
]
description = "A minimal graphics library in PyTorch"