#ifndef GFFX_CAPABILITIES_H
#define GFFX_CAPABILITIES_H

#include <gffx/status.h>

#define GFFX_CAPABILITY_CATEGORY_BUILD UINT32_C(1)
#define GFFX_CAPABILITY_CATEGORY_HOST UINT32_C(2)
#define GFFX_CAPABILITY_CATEGORY_CPU UINT32_C(3)
#define GFFX_CAPABILITY_CATEGORY_BACKEND UINT32_C(4)
#define GFFX_CAPABILITY_CATEGORY_DRIVER UINT32_C(5)
#define GFFX_CAPABILITY_CATEGORY_DEVICE UINT32_C(6)
#define GFFX_CAPABILITY_CATEGORY_OPERATION UINT32_C(7)

#define GFFX_CAPABILITY_VALUE_U64 UINT32_C(1)
#define GFFX_CAPABILITY_VALUE_I64 UINT32_C(2)
#define GFFX_CAPABILITY_VALUE_STRING UINT32_C(3)
#define GFFX_CAPABILITY_VALUE_BOOL UINT32_C(4)

#define GFFX_CAPABILITY_KEY_ABI_VERSION UINT32_C(1)
#define GFFX_CAPABILITY_KEY_PACKAGE_VERSION UINT32_C(2)
#define GFFX_CAPABILITY_KEY_POINTER_BITS UINT32_C(3)
#define GFFX_CAPABILITY_KEY_TARGET_OS UINT32_C(4)
#define GFFX_CAPABILITY_KEY_TARGET_ARCH UINT32_C(5)
#define GFFX_CAPABILITY_KEY_COMPILER UINT32_C(6)
#define GFFX_CAPABILITY_KEY_ENDIANNESS UINT32_C(7)
#define GFFX_CAPABILITY_KEY_CPU_BACKEND UINT32_C(8)
#define GFFX_CAPABILITY_KEY_CUDA_BACKEND UINT32_C(9)
#define GFFX_CAPABILITY_KEY_DTYPE_MASK UINT32_C(10)
#define GFFX_CAPABILITY_KEY_DEVICE_MASK UINT32_C(11)
#define GFFX_CAPABILITY_KEY_OPERATION_COUNT UINT32_C(12)
#define GFFX_CAPABILITY_KEY_CUDA_PROVIDER_STATUS UINT32_C(13)
#define GFFX_CAPABILITY_KEY_PROVIDER_STATUS UINT32_C(14)
#define GFFX_CAPABILITY_KEY_CUDA_PLUGIN_PATH UINT32_C(15)
#define GFFX_CAPABILITY_KEY_CUDA_PLUGIN_BUILD_ID UINT32_C(16)
#define GFFX_CAPABILITY_KEY_CUDA_PLUGIN_ABI_VERSION UINT32_C(17)
#define GFFX_CAPABILITY_KEY_CUDA_PLUGIN_COMPATIBLE UINT32_C(18)
#define GFFX_CAPABILITY_KEY_CUDA_DRIVER_STATUS UINT32_C(19)
#define GFFX_CAPABILITY_KEY_CUDA_DRIVER_VERSION UINT32_C(20)
#define GFFX_CAPABILITY_KEY_CUDA_DEVICE_COUNT UINT32_C(21)
#define GFFX_CAPABILITY_KEY_CUDA_TOOLKIT_VERSION UINT32_C(22)
#define GFFX_CAPABILITY_KEY_CUDA_DEVICE_NAME UINT32_C(23)
#define GFFX_CAPABILITY_KEY_CUDA_DEVICE_UUID UINT32_C(24)
#define GFFX_CAPABILITY_KEY_CUDA_DEVICE_PCI_BUS_ID UINT32_C(25)
#define GFFX_CAPABILITY_KEY_CUDA_COMPUTE_CAPABILITY_MAJOR UINT32_C(26)
#define GFFX_CAPABILITY_KEY_CUDA_COMPUTE_CAPABILITY_MINOR UINT32_C(27)
#define GFFX_CAPABILITY_KEY_CUDA_TOTAL_MEMORY_BYTES UINT32_C(28)
#define GFFX_CAPABILITY_KEY_CUDA_MULTIPROCESSOR_COUNT UINT32_C(29)
#define GFFX_CAPABILITY_KEY_CUDA_WARP_SIZE UINT32_C(30)
#define GFFX_CAPABILITY_KEY_CUDA_MAX_THREADS_PER_BLOCK UINT32_C(31)
#define GFFX_CAPABILITY_KEY_CUDA_MAX_BLOCK_DIM_X UINT32_C(32)
#define GFFX_CAPABILITY_KEY_CUDA_MAX_BLOCK_DIM_Y UINT32_C(33)
#define GFFX_CAPABILITY_KEY_CUDA_MAX_BLOCK_DIM_Z UINT32_C(34)
#define GFFX_CAPABILITY_KEY_CUDA_MAX_GRID_DIM_X UINT32_C(35)
#define GFFX_CAPABILITY_KEY_CUDA_MAX_GRID_DIM_Y UINT32_C(36)
#define GFFX_CAPABILITY_KEY_CUDA_MAX_GRID_DIM_Z UINT32_C(37)
#define GFFX_CAPABILITY_KEY_CUDA_SHARED_MEMORY_PER_BLOCK UINT32_C(38)
#define GFFX_CAPABILITY_KEY_CUDA_REGISTERS_PER_BLOCK UINT32_C(39)
#define GFFX_CAPABILITY_KEY_CUDA_CLOCK_RATE_KHZ UINT32_C(40)
#define GFFX_CAPABILITY_KEY_CUDA_MEMORY_CLOCK_RATE_KHZ UINT32_C(41)
#define GFFX_CAPABILITY_KEY_CUDA_MEMORY_BUS_WIDTH_BITS UINT32_C(42)
#define GFFX_CAPABILITY_KEY_CUDA_L2_CACHE_BYTES UINT32_C(43)
#define GFFX_CAPABILITY_KEY_CUDA_MAX_THREADS_PER_MULTIPROCESSOR UINT32_C(44)
#define GFFX_CAPABILITY_KEY_CUDA_UNIFIED_ADDRESSING UINT32_C(45)
#define GFFX_CAPABILITY_KEY_CUDA_MANAGED_MEMORY UINT32_C(46)
#define GFFX_CAPABILITY_KEY_CUDA_CONCURRENT_MANAGED_ACCESS UINT32_C(47)
#define GFFX_CAPABILITY_KEY_CUDA_PAGEABLE_MEMORY_ACCESS UINT32_C(48)
#define GFFX_CAPABILITY_KEY_CUDA_COOPERATIVE_LAUNCH UINT32_C(49)
#define GFFX_CAPABILITY_KEY_CUDA_COMPUTE_MODE UINT32_C(50)
#define GFFX_CAPABILITY_KEY_CUDA_KERNEL_TIMEOUT UINT32_C(51)
#define GFFX_CAPABILITY_KEY_CUDA_INTEGRATED UINT32_C(52)
#define GFFX_CAPABILITY_KEY_CUDA_CAN_MAP_HOST_MEMORY UINT32_C(53)
#define GFFX_CAPABILITY_KEY_CUDA_ASYNC_ENGINE_COUNT UINT32_C(54)
#define GFFX_CAPABILITY_KEY_CUDA_ECC_ENABLED UINT32_C(55)
#define GFFX_CAPABILITY_KEY_CUDA_TCC_DRIVER UINT32_C(56)
#define GFFX_CAPABILITY_KEY_CUDA_COMPUTE_PREEMPTION UINT32_C(57)
#define GFFX_CAPABILITY_KEY_CUDA_MAX_SHARED_MEMORY_PER_BLOCK_OPTIN UINT32_C(58)
#define GFFX_CAPABILITY_KEY_CUDA_MAX_BLOCKS_PER_MULTIPROCESSOR UINT32_C(59)
#define GFFX_CAPABILITY_KEY_CUDA_MEMORY_POOLS_SUPPORTED UINT32_C(60)
#define GFFX_CAPABILITY_KEY_CUDA_GPU_DIRECT_RDMA_SUPPORTED UINT32_C(61)

#define GFFX_CAPABILITY_RECORD_SENSITIVE UINT32_C(1)

#define GFFX_CAPABILITY_RESULT_STATIC UINT32_C(1)
#define GFFX_CAPABILITY_RESULT_RUNTIME_PROBED UINT32_C(2)
#define GFFX_CAPABILITY_RESULT_OPTIONAL_PROVIDER_ABSENT UINT32_C(4)
#define GFFX_CAPABILITY_RESULT_PARTIAL_FAILURE UINT32_C(8)

#define GFFX_CAPABILITY_PROBE_FULL UINT32_C(1)
#define GFFX_CAPABILITY_PROBE_INCLUDE_SENSITIVE UINT32_C(2)

typedef struct gffx_capability_record {
    uint32_t struct_size;
    uint32_t abi_version;
    uint32_t category;
    uint32_t subject_index;
    uint32_t key;
    uint32_t value_type;
    uint32_t flags;
    uint32_t reserved0;
    uint64_t value_u64;
    int64_t value_i64;
    uint64_t string_offset;
    uint64_t string_size;
    uint64_t reserved[4];
} gffx_capability_record;

typedef struct gffx_capability_report {
    uint32_t struct_size;
    uint32_t abi_version;
    gffx_capability_record *records;
    uint64_t record_capacity;
    uint64_t record_count;
    uint64_t required_record_count;
    char *strings;
    uint64_t string_capacity_bytes;
    uint64_t string_size_bytes;
    uint64_t required_string_bytes;
    uint32_t query_flags;
    uint32_t result_flags;
    uint64_t reserved[4];
} gffx_capability_report;

GFFX_EXTERN_C_BEGIN

GFFX_API gffx_status GFFX_CALL gffx_capabilities_query(
    gffx_capability_report *report,
    gffx_diagnostic_buffer *diagnostic
);

GFFX_API gffx_status GFFX_CALL gffx_capabilities_probe(
    uint32_t probe_flags,
    gffx_capability_report *report,
    gffx_diagnostic_buffer *diagnostic
);

GFFX_EXTERN_C_END

#endif /* GFFX_CAPABILITIES_H */
