"""Phase 3 Step 1 acceptance fixtures TA-01..TA-12 for the PyTorch CPU adapter.

Fixture numbers match TORCH_ADAPTER_ACCEPTANCE_V0_1.md in the project record.

Parity oracle. The record says fixtures compare against the C reference rather than against
hand-written values, which raises a bootstrapping problem: from Python the only route to the C
reference is the adapter under test. It is resolved with a committed oracle, tests/pytorch/
face_geometry_oracle.json, emitted by the C suite through examples/emit_face_geometry_oracle.c and
regenerated by that program rather than edited. The kernel stays the single source of truth, and no
expected value is transcribed by hand.

These fixtures are red until gffx.torch.mesh.face_geometry exists. They fail on a missing attribute,
not on a missing framework: gffx.torch imports successfully against PyTorch 2.10, and the module
gate and Stable-ABI binary are already verified by test_adapter_loading.py.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

torch = pytest.importorskip("torch")

ORACLE_PATH = Path(__file__).parent / "face_geometry_oracle.json"
EPS = 2.0 ** -20


def _adapter():
    """Resolve the operation under test, skipping nothing and failing loudly when absent."""
    import gffx.torch as adapter

    mesh = getattr(adapter, "mesh", None)
    assert mesh is not None, (
        "gffx.torch.mesh is not present. Phase 3 step 1 is what creates it; this is the "
        "expected red state before implementation."
    )
    operation = getattr(mesh, "face_geometry", None)
    assert operation is not None, "gffx.torch.mesh.face_geometry is not present"
    return operation


@pytest.fixture(scope="module")
def oracle():
    if not ORACLE_PATH.exists():
        pytest.fail(
            "the parity oracle %s is missing. Regenerate it by building and running "
            "gffx_emit_face_geometry_oracle; it is committed output, never hand-edited."
            % ORACLE_PATH.name
        )
    return json.loads(ORACLE_PATH.read_text())


def _case_tensors(case, vertex_dtype=torch.float64):
    vertices = torch.tensor(case["vertices"], dtype=vertex_dtype).reshape(-1, 3)
    faces = torch.tensor(case["faces"], dtype=torch.int32).reshape(-1, 3)
    return vertices, faces


# ------------------------------------------------------------------------------ TA-01, TA-02

def test_ta01_forward_parity(oracle):
    """Forward output is bit-identical to the C reference on the same inputs."""
    operation = _adapter()
    for case in oracle["cases"]:
        vertices, faces = _case_tensors(case)
        normals, areas, valid = operation(vertices, faces, eps=EPS)
        expected_normals = torch.tensor(case["unit_normals"], dtype=torch.float64).reshape(-1, 3)
        expected_areas = torch.tensor(case["areas"], dtype=torch.float64)
        expected_valid = torch.tensor(case["valid"], dtype=torch.bool)
        # Bit-exact: the adapter performs no arithmetic of its own, so any difference is a
        # conversion defect rather than a numerical one.
        assert torch.equal(normals, expected_normals), case["name"]
        assert torch.equal(areas, expected_areas), case["name"]
        assert torch.equal(valid, expected_valid), case["name"]


def test_ta02_vertex_dtypes(oracle):
    """float32 and float64 are accepted and select the computation dtype; narrower types are not."""
    operation = _adapter()
    case = oracle["cases"][0]

    wide_vertices, faces = _case_tensors(case, torch.float64)
    narrow_vertices, _ = _case_tensors(case, torch.float32)
    wide_normals, wide_areas, _ = operation(wide_vertices, faces, eps=EPS)
    narrow_normals, narrow_areas, _ = operation(narrow_vertices, faces, eps=EPS)
    assert wide_normals.dtype == torch.float64
    assert narrow_normals.dtype == torch.float32
    assert wide_areas.dtype == torch.float64
    assert narrow_areas.dtype == torch.float32

    for bad in (torch.float16, torch.bfloat16):
        with pytest.raises(TypeError):
            operation(wide_vertices.to(bad), faces, eps=EPS)


# ------------------------------------------------------------------------------ TA-03, TA-04, TA-05

def test_ta03_non_contiguous_is_refused(oracle):
    """A non-contiguous view raises rather than being silently copied."""
    operation = _adapter()
    case = oracle["cases"][0]
    vertices, faces = _case_tensors(case)

    padded = torch.zeros((vertices.shape[0], 6), dtype=torch.float64)
    padded[:, :3] = vertices
    strided = padded[:, :3]
    assert not strided.is_contiguous()
    with pytest.raises(ValueError):
        operation(strided, faces, eps=EPS)

    transposed = vertices.t().t()
    if not transposed.is_contiguous():
        with pytest.raises(ValueError):
            operation(transposed, faces, eps=EPS)


def test_ta04_int64_faces_are_refused(oracle):
    """int64 topology raises, and the message points at the explicit conversion."""
    operation = _adapter()
    case = oracle["cases"][0]
    vertices, faces = _case_tensors(case)
    with pytest.raises(TypeError) as caught:
        operation(vertices, faces.to(torch.int64), eps=EPS)
    message = str(caught.value)
    assert "int32" in message, "the message must name the required dtype"


def test_ta05_non_cpu_device_is_refused(oracle):
    """A non-CPU tensor raises a clear error rather than crashing."""
    operation = _adapter()
    if not torch.cuda.is_available():
        pytest.skip("no CUDA device present; this fixture needs one to be meaningful")
    case = oracle["cases"][0]
    vertices, faces = _case_tensors(case)
    with pytest.raises(ValueError):
        operation(vertices.cuda(), faces.cuda(), eps=EPS)


# ------------------------------------------------------------------------------ TA-06..TA-08

def test_ta06_backward_parity(oracle):
    """Gradients are bit-identical to the C backward on the same cotangents."""
    operation = _adapter()
    for case in oracle["cases"]:
        if "grad_vertices" not in case:
            continue
        vertices, faces = _case_tensors(case)
        vertices.requires_grad_(True)
        normals, areas, _ = operation(vertices, faces, eps=EPS)
        grad_normals = torch.tensor(
            case["grad_unit_normals"], dtype=torch.float64).reshape(-1, 3)
        grad_areas = torch.tensor(case["grad_areas"], dtype=torch.float64)
        (normals * grad_normals).sum().add((areas * grad_areas).sum()).backward()
        expected = torch.tensor(case["grad_vertices"], dtype=torch.float64).reshape(-1, 3)
        assert torch.equal(vertices.grad, expected), case["name"]


def test_ta07_gradcheck(oracle):
    """The registered formula agrees with numerical differentiation."""
    operation = _adapter()
    case = oracle["cases"][0]
    vertices, faces = _case_tensors(case)
    vertices.requires_grad_(True)

    def only_areas(v):
        _, areas, _ = operation(v, faces, eps=EPS)
        return areas

    assert torch.autograd.gradcheck(only_areas, (vertices,), eps=1e-6, atol=1e-8)


def test_ta08_absent_cotangents(oracle):
    """One absent cotangent is honoured; both absent is an error."""
    operation = _adapter()
    case = oracle["cases"][0]
    vertices, faces = _case_tensors(case)
    vertices.requires_grad_(True)

    # Only the areas cotangent flows: the normals branch contributes exactly zero.
    _, areas, _ = operation(vertices, faces, eps=EPS)
    areas.sum().backward()
    assert vertices.grad is not None
    assert torch.isfinite(vertices.grad).all()


# ------------------------------------------------------------------------------ TA-09..TA-12

def test_ta09_error_mapping(oracle):
    """Each reachable ABI status maps to its documented Python exception."""
    operation = _adapter()
    case = oracle["cases"][0]
    vertices, faces = _case_tensors(case)

    # INVALID_ARGUMENT: a face index outside [0, V).
    bad_faces = faces.clone()
    bad_faces[0, 0] = 10_000
    with pytest.raises(ValueError) as caught:
        operation(vertices, bad_faces, eps=EPS)
    assert str(caught.value), "the diagnostic text must reach the message"

    # INVALID_ARGUMENT: a negative eps.
    with pytest.raises(ValueError):
        operation(vertices, faces, eps=-1.0)


def test_ta10_input_immutability(oracle):
    """No input tensor is modified by a forward or a backward call."""
    operation = _adapter()
    case = oracle["cases"][0]
    vertices, faces = _case_tensors(case)
    vertices_before = vertices.clone()
    faces_before = faces.clone()

    operation(vertices, faces, eps=EPS)
    assert torch.equal(vertices, vertices_before)
    assert torch.equal(faces, faces_before)

    grad_vertices = vertices.clone().requires_grad_(True)
    _, areas, _ = operation(grad_vertices, faces, eps=EPS)
    areas.sum().backward()
    assert torch.equal(faces, faces_before)


def test_ta11_determinism(oracle):
    """Repeated identical calls produce bit-identical outputs."""
    operation = _adapter()
    case = oracle["cases"][0]
    vertices, faces = _case_tensors(case)
    first = operation(vertices, faces, eps=EPS)
    second = operation(vertices, faces, eps=EPS)
    for a, b in zip(first, second):
        assert torch.equal(a, b)


def test_ta12_out_surface(oracle):
    """The inference-only surface writes preallocated outputs and refuses tracked inputs."""
    import gffx.torch as adapter

    stream = getattr(adapter, "stream", None)
    assert stream is not None, (
        "gffx.torch.stream is not present. Phase 3 step 1 is what creates it; this is the "
        "expected red state before implementation."
    )
    operation_out = getattr(stream, "face_geometry_out", None)
    assert operation_out is not None, "gffx.torch.stream.face_geometry_out is not present"

    functional = _adapter()
    case = oracle["cases"][0]
    vertices, faces = _case_tensors(case)
    expected_normals, expected_areas, expected_valid = functional(vertices, faces, eps=EPS)

    normals = torch.empty_like(expected_normals)
    areas = torch.empty_like(expected_areas)
    valid = torch.empty_like(expected_valid)
    workspace = torch.empty(0, dtype=torch.uint8)
    operation_out(
        vertices, faces, eps=EPS,
        outputs=(normals, areas, valid), workspace=workspace,
    )
    assert torch.equal(normals, expected_normals)
    assert torch.equal(areas, expected_areas)
    assert torch.equal(valid, expected_valid)

    tracked = vertices.clone().requires_grad_(True)
    with pytest.raises(ValueError):
        operation_out(
            tracked, faces, eps=EPS,
            outputs=(normals, areas, valid), workspace=workspace,
        )


# ------------------------------------------------------------------------------ TA-13

def test_ta13_single_face_gradient():
    """A one-face mesh differentiates.

    Regression fixture for a defect the other twelve missed. `loss.sum().backward()` hands back an
    expanded cotangent with stride 0, and torch reports a size-1 dimension as contiguous whatever
    its stride, so `.contiguous()` left the zero stride in place and the ABI refused it. Every
    oracle case has more than one face, so nothing exercised the size-1 path.
    """
    operation = _adapter()
    vertices = torch.tensor(
        [[0.0, 0.0, 0.0], [1.0, 0.0, 0.0], [0.0, 1.0, 0.0]], dtype=torch.float64,
        requires_grad=True,
    )
    faces = torch.tensor([[0, 1, 2]], dtype=torch.int32)

    _, areas, _ = operation(vertices, faces, eps=EPS)
    areas.sum().backward()
    assert vertices.grad is not None
    assert torch.isfinite(vertices.grad).all()

    # The same path through the normals cotangent, which is [1, 3] rather than [1].
    vertices2 = vertices.detach().clone().requires_grad_(True)
    normals, _, _ = operation(vertices2, faces, eps=EPS)
    normals.sum().backward()
    assert torch.isfinite(vertices2.grad).all()
