# Embeds a compiled PTX module into the plugin as generated C source.
#
# The plugin carries its kernels inside its own binary rather than loading a .ptx file beside it at
# runtime. A file would be a second artifact to install, to find, to version against the plugin, and
# to fail on when absent or stale; embedding removes all four failure modes and keeps the plugin a
# single self-describing object. It also means the kernels cannot drift from the loader that
# launches them, because they ship as one build product.
#
# PTX is text, but it is emitted as a byte array rather than a C string literal: a literal would
# need escaping, would run into implementation limits on string length, and would be unreadable in
# a diff. The array is NUL-terminated because cuModuleLoadData takes a NUL-terminated image.
#
# Run in script mode:
#   cmake -DGFFX_PTX_INPUT=<file> -DGFFX_PTX_OUTPUT=<file> -DGFFX_PTX_SYMBOL=<name>
#         -P GffxEmbedPtx.cmake

cmake_minimum_required(VERSION 3.25)

foreach(required GFFX_PTX_INPUT GFFX_PTX_OUTPUT GFFX_PTX_SYMBOL)
    if(NOT DEFINED ${required})
        message(FATAL_ERROR "${required} must be defined")
    endif()
endforeach()

if(NOT EXISTS "${GFFX_PTX_INPUT}")
    message(FATAL_ERROR "PTX input not found: ${GFFX_PTX_INPUT}")
endif()

file(READ "${GFFX_PTX_INPUT}" ptx_hex HEX)
string(LENGTH "${ptx_hex}" hex_length)
math(EXPR byte_count "${hex_length} / 2")
if(byte_count EQUAL 0)
    message(FATAL_ERROR "PTX input is empty: ${GFFX_PTX_INPUT}")
endif()

# Extract the .version and .target directives so the generated file records what it carries. These
# are the two properties that decide which drivers can parse the module and which GPUs it reaches,
# so they belong in the artifact rather than only in a build log.
file(STRINGS "${GFFX_PTX_INPUT}" ptx_version REGEX "^\\.version")
file(STRINGS "${GFFX_PTX_INPUT}" ptx_target REGEX "^\\.target")
if(ptx_version STREQUAL "")
    set(ptx_version "unknown")
endif()
if(ptx_target STREQUAL "")
    set(ptx_target "unknown")
endif()

set(body "")
set(column 0)
set(index 0)
while(index LESS hex_length)
    string(SUBSTRING "${ptx_hex}" ${index} 2 byte)
    string(APPEND body "0x${byte},")
    math(EXPR column "${column} + 1")
    if(column EQUAL 16)
        string(APPEND body "\n    ")
        set(column 0)
    else()
        string(APPEND body " ")
    endif()
    math(EXPR index "${index} + 2")
endwhile()

get_filename_component(input_name "${GFFX_PTX_INPUT}" NAME)

file(WRITE "${GFFX_PTX_OUTPUT}"
"/* Generated by cmake/GffxEmbedPtx.cmake from ${input_name}. Do not edit.\n"
" *\n"
" * PTX ${ptx_version}, ${ptx_target}. The target is the architecture floor, not the build\n"
" * machine's GPU: the driver JIT-compiles this module for whatever device is present, including\n"
" * architectures that did not exist when it was compiled. The ISA version is a property of the\n"
" * build toolkit and sets the minimum driver that can parse it.\n"
" */\n"
"\n"
"static const unsigned char ${GFFX_PTX_SYMBOL}[] = {\n    ${body}0x00\n};\n"
"\n"
"static const unsigned long ${GFFX_PTX_SYMBOL}_size = ${byte_count}UL;\n"
)

message(STATUS "embedded ${byte_count} bytes of PTX (${ptx_version}, ${ptx_target})")
